### ISSUE TITLE
Number is not centered vertically in OTP view

### ISSUE THREAD

**Issue by MohamedHefny** [osamasayed585/Verify-Swift#1]
Thanks @osamasayed585 for creating this library. I've tried it on the go and found that the number is not well centered inside the OTP view especially the circle one. Please check the attached screenshot.
![Screenshot_20231218_230023](https://github.com/osamasayed585/Verify-Swift/assets/16237969/f043167e-1148-4c77-9605-3d1a0c7a7c7b)

**Comment by osamasayed585** [comment]
Hi @MohamedHefny

Thank you so much for trying out Verify-Swift and for bringing this to my attention! 🙌 I appreciate your feedback
I've noted it and will work on a fix for the upcoming update. Stay tuned!

**Comment by osamasayed585** [comment]
Hi @MohamedHefny 
Issue resolved! Thank you for pointing it out. Here's the result after the update.

![image](https://github.com/osamasayed585/Verify-Swift/assets/68209547/fd64ff44-23f2-4a74-bd7d-b27f332619b6)
